[[abbrevs]]
name = "open CUE files"
abbr = "oc"
snippet = "fd -e cue -0 . ~/Music/CD | xargs -0 nvim"

# YT-DLP
[[abbrevs]]
name = "yt-dlp"
abbr = "ytd"
snippet = "yt-dlp"
[[abbrevs]]
name = "yt-dlp bestaudio"
abbr = "ytdba"
snippet = "yt-dlp -f bestaudio"
[[abbrevs]]
name = "yt-dlp download to Download-Directory"
abbr = "ytdd"
snippet = "yt-dlp --paths ~/Downloads"
[[abbrevs]]
name = "yt-dlp using List file"
abbr = "list"
snippet = "-a ~/Downloads/yt-dlp-list.txt"
global = true
context = "^yt-dlp*"
[[abbrevs]]
name = "yt-dlp HD"
abbr = "ytdhd"
snippet = "yt-dlp -f \"bv[ext=mp4]+ba[ext=m4a]\" --merge-output-format mp4 --write-thumbnail -o '~/Movies/YouTube/%(channel)s/%(upload_date)s %(title)s [%(id)s].%(ext)s'"
[[abbrevs]]
name = "yt-dlp 4K"
abbr = "ytd4k"
snippet = "yt-dlp -f \"bv[ext=webm]+ba[ext=webm]\" --merge-output-format webm --recode-video mp4 --write-thumbnail -o '~/Movies/YouTube/%(channel)s/%(upload_date)s %(title)s [%(id)s].%(ext)s'"
