[[[abbrevs]]
name = "git"
abbr = "g"
snippet = 'git'
[[[abbrevs]]
name = "git add"
abbr = "gad"
snippet = 'git add'
[[[abbrevs]]
name = "git add current all"
abbr = "gad."
snippet = 'git add .'
[[[abbrevs]]
name = "git branch"
abbr = "gbr"
snippet = 'git branch'
[[[abbrevs]]
name = "git commit"
abbr = "gcm"
snippet = 'git commit -m "{}"'
[[[abbrevs]]
name = "git status"
abbr = "gst"
snippet = 'git status'
[[[abbrevs]]
name = "git chekout"
abbr = "gco"
snippet = 'git chekout'
[[[abbrevs]]
name = "git diff"
abbr = "gdf"
snippet = 'git diff'
[[[abbrevs]]
name = "git log"
abbr = 'glg'
snippet = 'git log'
[[[abbrevs]]
name = "git pull"
abbr = "gpl"
snippet = 'git pull'
[[[abbrevs]]
name = "git push"
abbr = "gps"
snippet = 'git push'
